export const FETCH_PRODUCT_DONE = 'FETCH_PRODUCT_DONE'
export const FETCH_PRODUCT_FAIL = 'FETCH_PRODUCT_DONE'


export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'


export const  SIGNUP_REQUEST = ' SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'


export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const UPDATE_PRODUCT_COUNT = 'UPDATE_PRODUCT_COUNT';

export const ADD_TO_CHECKOUT  = 'ADD_TO_CHECKOUT ';

export const  LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'